# Generated by Django 4.0.2 on 2022-02-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoklamamodulu', '0002_hoca_features_ogrenci_features_delete_user_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isim',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='soyisim',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
